# Generated by Django 4.2.25 on 2025-11-07 06:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Porcentaje'), ('AMOUNT', 'Monto fijo')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('CATEGORY', 'Categoria'), ('PRODUCT', 'Producto')], default='GLOBAL', max_length=16)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gt', 0)), name='promotion_discount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('discount_type', 'PERCENT'), ('discount_value__lte', 100)), ('discount_type', 'AMOUNT'), _connector='OR'), name='promotion_percent_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='promotion_end_after_start'),
        ),
    ]
