# Generated by Django 4.2.25 on 2025-11-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushtoken',
            new_name='notificatio_platfor_1c038a_idx',
            old_name='notifications_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='pushtoken',
            new_name='notificatio_user_id_cbc779_idx',
            old_name='notifications_user_platform_idx',
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20),
        ),
    ]
