# Generated by Django 4.2.25 on 2025-11-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_orderitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En proceso'), ('IN_TRANSIT', 'En camino'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20),
        ),
    ]
