"""
Seed demo categories and products.

Usage:
    python manage.py shell < backend/scripts/seed_demo_data.py
"""

from decimal import Decimal

from catalog.models import Category, Product, ProductFeature


CATEGORIES = [
    {
        "name": "Electrodomésticos Inteligentes",
        "description": "Equipos conectados que automatizan tareas del hogar y se integran con apps móviles.",
        "image_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=80",
    },
    {
        "name": "Tecnología Personal",
        "description": "Wearables y gadgets para productividad y bienestar.",
        "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=80",
    },
    {
        "name": "Oficina y productividad",
        "description": "Equipamiento para espacios de trabajo híbridos y home office.",
        "image_url": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1000&q=80",
    },
    {
        "name": "Cocina profesional",
        "description": "Herramientas de cocina premium para emprendedores gastronómicos.",
        "image_url": "https://images.unsplash.com/photo-1503009549120-0ad6b353e2b3?auto=format&fit=crop&w=1000&q=80",
    },
    {
        "name": "Gaming y entretenimiento",
        "description": "Accesorios de alto desempeño para gamers y creadores de contenido.",
        "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1000&q=80",
    },
]


PRODUCTS = [
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Robot aspirador SmartSweep X5",
        "sku": "SSX5-001",
        "price": Decimal("329.99"),
        "stock": 35,
        "short_description": "Mapeo láser, control por voz y base de auto-vaciado.",
        "long_description": "El SmartSweep X5 limpia pisos duros y alfombras con navegación LiDAR 360°, integración con Alexa/Google Home y autonomía de 180 minutos.",
        "width_cm": Decimal("35"),
        "height_cm": Decimal("9"),
        "weight_kg": Decimal("3.50"),
        "cover_image_url": "https://images.unsplash.com/photo-1581579185169-7798334ecd2d?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Purificador de aire PureSense Pro",
        "sku": "PSP-210",
        "price": Decimal("249.00"),
        "stock": 22,
        "short_description": "Filtro HEPA H13 y seguimiento de calidad del aire en app.",
        "long_description": "Purifica hasta 60 m², elimina el 99.97% de partículas y ajusta la velocidad automáticamente según los sensores integrados.",
        "width_cm": Decimal("28"),
        "height_cm": Decimal("55"),
        "weight_kg": Decimal("6.20"),
        "cover_image_url": "https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Smartwatch Vital Band 4",
        "sku": "VB4-802",
        "price": Decimal("189.50"),
        "stock": 50,
        "short_description": "ECG, oxímetro y métricas de entrenamiento avanzadas.",
        "long_description": "Pantalla AMOLED de 1.65'', GPS integrado, resistencia 5 ATM y autonomía de 10 días.",
        "width_cm": Decimal("4"),
        "height_cm": Decimal("1.2"),
        "weight_kg": Decimal("0.05"),
        "cover_image_url": "https://images.unsplash.com/photo-1516575150278-77136aed6920?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Auriculares inalámbricos EchoPods Studio",
        "sku": "EPS-450",
        "price": Decimal("149.90"),
        "stock": 60,
        "short_description": "Cancelación activa híbrida y modo transparencia inteligente.",
        "long_description": "Drivers de 40 mm, audio espacial, carga rápida USB-C y hasta 35 horas de reproducción.",
        "width_cm": Decimal("18"),
        "height_cm": Decimal("20"),
        "weight_kg": Decimal("0.24"),
        "cover_image_url": "https://images.unsplash.com/photo-1511367466-95bf97d5433c?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Monitor ultrawide FocusView 34\"",
        "sku": "FV34-UW",
        "price": Decimal("599.00"),
        "stock": 18,
        "short_description": "Panel QHD curvo con USB-C y hub integrado.",
        "long_description": "Ideal para multitarea y edición, cubre el 99% sRGB y entrega hasta 90W de carga a laptops vía USB-C.",
        "width_cm": Decimal("81"),
        "height_cm": Decimal("46"),
        "weight_kg": Decimal("8.30"),
        "cover_image_url": "https://images.unsplash.com/photo-1587613865763-4b8b0b09b445?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Silla ergonómica ErgoMesh Pro",
        "sku": "EMP-710",
        "price": Decimal("379.00"),
        "stock": 25,
        "short_description": "Soporte lumbar 4D y malla transpirable.",
        "long_description": "Base de aluminio, reposacabezas ajustable y certificación BIFMA para uso intensivo.",
        "width_cm": Decimal("70"),
        "height_cm": Decimal("120"),
        "weight_kg": Decimal("18.00"),
        "cover_image_url": "https://images.unsplash.com/photo-1587613999823-74daaa3ca4cd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Horno inteligente SteamChef 40L",
        "sku": "SC40-900",
        "price": Decimal("799.00"),
        "stock": 12,
        "short_description": "Combina vapor, convección y control remoto.",
        "long_description": "Permite programar recetas desde la app, tiene sonda térmica y limpieza automática a vapor.",
        "width_cm": Decimal("59.5"),
        "height_cm": Decimal("45"),
        "weight_kg": Decimal("32.0"),
        "cover_image_url": "https://images.unsplash.com/photo-1506368083636-6defb67639c2?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Licuadora industrial BlendForce 3HP",
        "sku": "BF3-1200",
        "price": Decimal("269.00"),
        "stock": 30,
        "short_description": "Motor de 3 caballos y vaso tritán de 2L.",
        "long_description": "Perfecta para smoothies y salsas de alto volumen, incluye 6 programas automáticos y panel táctil.",
        "width_cm": Decimal("23"),
        "height_cm": Decimal("52"),
        "weight_kg": Decimal("5.60"),
        "cover_image_url": "https://images.unsplash.com/photo-1505576391880-b3f9d713dc0c?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Silla gamer RGB ThunderStrike",
        "sku": "TS-RGB",
        "price": Decimal("289.90"),
        "stock": 40,
        "short_description": "Iluminación direccionable y cojines de memoria.",
        "long_description": "Soporta hasta 150 kg, reposabrazos 4D y modo reclinable 155°.",
        "width_cm": Decimal("72"),
        "height_cm": Decimal("128"),
        "weight_kg": Decimal("21.0"),
        "cover_image_url": "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Teclado mecánico Aurora TKL",
        "sku": "ATKL-002",
        "price": Decimal("119.00"),
        "stock": 55,
        "short_description": "Switches hot-swap y triple conexión (USB, BT, 2.4G).",
        "long_description": "Layout tenkeyless con keycaps PBT y 17 efectos de iluminación.",
        "width_cm": Decimal("36"),
        "height_cm": Decimal("4"),
        "weight_kg": Decimal("0.9"),
        "cover_image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Cafetera inteligente BaristaLink",
        "sku": "BLK-580",
        "price": Decimal("219.00"),
        "stock": 28,
        "short_description": "Programable con recetas personalizadas y app móvil.",
        "long_description": "Cafetera espresso de 15 bares con control remoto, perfiles de usuario y mantenimiento guiado.",
        "width_cm": Decimal("24"),
        "height_cm": Decimal("32"),
        "weight_kg": Decimal("5.2"),
        "cover_image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Lavadora SmartWash 12kg",
        "sku": "SW-1200",
        "price": Decimal("679.00"),
        "stock": 15,
        "short_description": "Dosificador automático y ciclos guiados por IA.",
        "long_description": "Control desde la app, autolimpieza del tambor y diagnósticos en tiempo real.",
        "width_cm": Decimal("59"),
        "height_cm": Decimal("85"),
        "weight_kg": Decimal("63"),
        "cover_image_url": "https://images.unsplash.com/photo-1511407397940-d57f68e81203?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Sistema de seguridad HomeGuard 360",
        "sku": "HG360",
        "price": Decimal("349.00"),
        "stock": 40,
        "short_description": "Kit de cámaras 4K, sensores y hub con almacenamiento local.",
        "long_description": "Incluye detección de personas, alertas push y compatibilidad con HomeKit.",
        "width_cm": Decimal("30"),
        "height_cm": Decimal("25"),
        "weight_kg": Decimal("4.5"),
        "cover_image_url": "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Gafas AR VisionPro Lite",
        "sku": "VPL-700",
        "price": Decimal("899.00"),
        "stock": 10,
        "short_description": "Realidad aumentada para productividad y asistencia remota.",
        "long_description": "Pantallas micro-OLED, batería intercambiable y transmisión segura mediante 5G.",
        "width_cm": Decimal("18"),
        "height_cm": Decimal("5"),
        "weight_kg": Decimal("0.32"),
        "cover_image_url": "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Router WiFi 6E Mesh TriBand",
        "sku": "MESH-6E",
        "price": Decimal("299.00"),
        "stock": 25,
        "short_description": "Cobertura hasta 600 m² con seguridad WPA3 y control parental.",
        "long_description": "Incluye 2 nodos, puertos 2.5G y aplicación móvil con diagnósticos en tiempo real.",
        "width_cm": Decimal("11"),
        "height_cm": Decimal("19"),
        "weight_kg": Decimal("0.8"),
        "cover_image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Dock USB-C Productivity Hub",
        "sku": "PDH-606",
        "price": Decimal("139.00"),
        "stock": 70,
        "short_description": "Dock 11-en-1 con soporte vertical y carga 100W.",
        "long_description": "Proporciona HDMI dual, Ethernet 2.5G, lector SD y switch KVM integrado.",
        "width_cm": Decimal("20"),
        "height_cm": Decimal("5"),
        "weight_kg": Decimal("0.6"),
        "cover_image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Lampara inteligente FocusBeam",
        "sku": "FB-330",
        "price": Decimal("89.00"),
        "stock": 90,
        "short_description": "Ajuste automático según la luz ambiente y temporizador pomodoro.",
        "long_description": "Iluminación LED CRI95, puerto de carga inalámbrica y recordatorios de postura.",
        "width_cm": Decimal("18"),
        "height_cm": Decimal("45"),
        "weight_kg": Decimal("1.5"),
        "cover_image_url": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Selladora al vacío ProSeal Duo",
        "sku": "PSD-220",
        "price": Decimal("159.00"),
        "stock": 32,
        "short_description": "Sellado dual y modo marinado para restaurantes.",
        "long_description": "Incluye rollos reutilizables, control táctil y opción de vacío externo para frascos.",
        "width_cm": Decimal("41"),
        "height_cm": Decimal("12"),
        "weight_kg": Decimal("2.9"),
        "cover_image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Plancha Teppan NitroHeat",
        "sku": "NH-3300",
        "price": Decimal("549.00"),
        "stock": 14,
        "short_description": "Placa de acero al carbono con control preciso de temperatura.",
        "long_description": "Superficie de 60 cm, sensor digital y acabado antiadherente apto para limpieza industrial.",
        "width_cm": Decimal("60"),
        "height_cm": Decimal("15"),
        "weight_kg": Decimal("26.5"),
        "cover_image_url": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Control inalámbrico PulseEdge",
        "sku": "PE-550",
        "price": Decimal("89.90"),
        "stock": 80,
        "short_description": "Compatible con PC/Consola, trigger háptico y centro de macros.",
        "long_description": "Batería de 20 h, conectividad multipunto y grips reemplazables.",
        "width_cm": Decimal("16"),
        "height_cm": Decimal("7"),
        "weight_kg": Decimal("0.28"),
        "cover_image_url": "https://images.unsplash.com/photo-1606813902914-cc9001182388?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Micrófono streaming EchoCast Pro",
        "sku": "ECP-900",
        "price": Decimal("179.00"),
        "stock": 33,
        "short_description": "Micrófono XLR/USB con DSP integrado y iluminación RGB.",
        "long_description": "Incluye brazo articulado, filtro antipop magnético y perfiles configurables.",
        "width_cm": Decimal("12"),
        "height_cm": Decimal("25"),
        "weight_kg": Decimal("0.9"),
        "cover_image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Mochila antirrobo SafeCommute",
        "sku": "SCM-350",
        "price": Decimal("99.00"),
        "stock": 65,
        "short_description": "Compartimento RFID, cargador USB y tela resistente al agua.",
        "long_description": "Diseño expandible 18-26L con cierre oculto y bolsillo para laptop 16”.",
        "width_cm": Decimal("30"),
        "height_cm": Decimal("45"),
        "weight_kg": Decimal("1.1"),
        "cover_image_url": "https://images.unsplash.com/photo-1518559241500-73ee5992731a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Estación modular FlexDesk Pro",
        "sku": "FDP-400",
        "price": Decimal("459.00"),
        "stock": 20,
        "short_description": "Escritorio elevable eléctrico con memorias y hub integrado.",
        "long_description": "Rango 62-125 cm, superficie antibacteriana y organización magnética de cables.",
        "width_cm": Decimal("140"),
        "height_cm": Decimal("12"),
        "weight_kg": Decimal("42"),
        "cover_image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Termocirculador SousChef Pro",
        "sku": "SCP-550",
        "price": Decimal("189.00"),
        "stock": 37,
        "short_description": "Precisión de ±0.05°C y conectividad Bluetooth.",
        "long_description": "Calienta hasta 40 L de agua, programas personalizados y notificaciones en móvil.",
        "width_cm": Decimal("11"),
        "height_cm": Decimal("38"),
        "weight_kg": Decimal("1.3"),
        "cover_image_url": "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Monitor portátil StreamView 15\"",
        "sku": "SV15-600",
        "price": Decimal("229.00"),
        "stock": 48,
        "short_description": "Pantalla FHD plegable con altavoces duales para streamers.",
        "long_description": "Compatible con consolas y laptops, incluye funda soporte y entrada mini-HDMI.",
        "width_cm": Decimal("36"),
        "height_cm": Decimal("22"),
        "weight_kg": Decimal("1.2"),
        "cover_image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Electrodomésticos Inteligentes",
        "name": "Humidificador aroma SenseMist",
        "sku": "SM-210",
        "price": Decimal("69.90"),
        "stock": 75,
        "short_description": "Nebulización ultrasónica y luz ambiental RGB.",
        "long_description": "Tanque de 3L, modo silencioso y programación desde la app móvil.",
        "width_cm": Decimal("17"),
        "height_cm": Decimal("28"),
        "weight_kg": Decimal("1.4"),
        "cover_image_url": "https://images.unsplash.com/photo-1502740479091-635887520276?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Power bank SolarGo 30k",
        "sku": "SG30K",
        "price": Decimal("129.00"),
        "stock": 55,
        "short_description": "Celdas solares, carga inalámbrica y salida 100W USB-C.",
        "long_description": "Resistente al agua IP67, pantalla de estado y modo linterna SOS.",
        "width_cm": Decimal("18"),
        "height_cm": Decimal("3"),
        "weight_kg": Decimal("0.95"),
        "cover_image_url": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Panel acústico modular QuietWave",
        "sku": "QW-120",
        "price": Decimal("74.00"),
        "stock": 120,
        "short_description": "Paneles magnéticos para aislar ruido en oficinas.",
        "long_description": "Pack de 6 unidades, absorción NRC 0.85 y acabado textil premium.",
        "width_cm": Decimal("30"),
        "height_cm": Decimal("30"),
        "weight_kg": Decimal("0.4"),
        "cover_image_url": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Planificador digital FoodCost",
        "sku": "FD-APP",
        "price": Decimal("49.00"),
        "stock": 200,
        "short_description": "Suscripción anual para calcular costos y mermas.",
        "long_description": "Aplicación basada en la nube con integración POS y reportes descargables.",
        "width_cm": Decimal("0"),
        "height_cm": Decimal("0"),
        "weight_kg": Decimal("0.0"),
        "cover_image_url": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Gaming y entretenimiento",
        "name": "Kit iluminación StreamRGB Nano",
        "sku": "SRGB-NANO",
        "price": Decimal("139.00"),
        "stock": 45,
        "short_description": "Paneles hexagonales con control por voz y escenas dinámicas.",
        "long_description": "Adhesivo reutilizable, sincronización música y compatibilidad con Razer Chroma.",
        "width_cm": Decimal("34"),
        "height_cm": Decimal("3"),
        "weight_kg": Decimal("0.7"),
        "cover_image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Tecnología Personal",
        "name": "Lector biométrico SecurePad Mini",
        "sku": "SPM-220",
        "price": Decimal("139.00"),
        "stock": 40,
        "short_description": "Autenticador FIDO2 con sensor de huella y NFC.",
        "long_description": "Compatible con Windows Hello, macOS y servicios en la nube, incluye estuche magnético.",
        "width_cm": Decimal("6"),
        "height_cm": Decimal("1.5"),
        "weight_kg": Decimal("0.07"),
        "cover_image_url": "https://images.unsplash.com/photo-1517430816045-df4b7deef7d6?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Oficina y productividad",
        "name": "Webcam 4K UltraMeet",
        "sku": "UM-4K",
        "price": Decimal("159.00"),
        "stock": 52,
        "short_description": "Auto framing, HDR y cancelación de ruido AI.",
        "long_description": "Incluye obturador físico, montaje magnético y software multipantalla.",
        "width_cm": Decimal("12"),
        "height_cm": Decimal("4"),
        "weight_kg": Decimal("0.2"),
        "cover_image_url": "https://images.unsplash.com/photo-1593642532744-d377ab507dc8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category": "Cocina profesional",
        "name": "Dispensador DualSauce Pro",
        "sku": "DSP-450",
        "price": Decimal("129.00"),
        "stock": 48,
        "short_description": "Mantiene salsas a temperatura ideal con control digital.",
        "long_description": "Dos contenedores de acero 2L, limpieza rápida y alarmas personalizadas.",
        "width_cm": Decimal("42"),
        "height_cm": Decimal("23"),
        "weight_kg": Decimal("6"),
        "cover_image_url": "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=900&q=80",
    },
]


def main() -> None:
    created_categories = 0
    for category in CATEGORIES:
        _, created = Category.objects.get_or_create(
            name=category["name"],
            defaults={"description": category["description"], "image_url": category["image_url"]},
        )
        if created:
            created_categories += 1

    created_products = 0
    for product in PRODUCTS:
        category = Category.objects.get(name=product["category"])
        defaults = {k: v for k, v in product.items() if k not in {"category", "sku", "name"}}
        _, created = Product.objects.get_or_create(
            sku=product["sku"],
            defaults={"category": category, "name": product["name"], **defaults},
        )
        if created:
            created_products += 1

    print(f"Categorias creadas: {created_categories} | Productos creados: {created_products}")


if __name__ == "__main__":
    main()
