# Generated by Django 4.2.25 on 2025-11-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='activity_au_event_t_9ed639_idx',
            old_name='activity_a_event_t_7274a4_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='activity_au_entity__bcf339_idx',
            old_name='activity_a_entity__4f59b1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='activity_au_created_fcd391_idx',
            old_name='activity_a_created__ec2d0e_idx',
        ),
    ]
