# Generated by Django 4.2.25 on 2025-10-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='authx_email_user_id_9a2db4_idx',
            old_name='authx_email_user_pu_9acf76_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
